#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Code is generated by Telerik Data Access Service Wizard
// using Astoria1DataServiceKeys.tt template

namespace lahman_odata
{
	using System.Data.Services.Common;
	using System;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.Serialization;

	/// <summary>
	/// Denotes the key property or properties of an entity master.
	/// Any class with this attribute is considered an entity type in OData protocol.
	/// </summary>
	[DataServiceKey("playerid")]
	public partial class master
	{
	}
}
#pragma warning restore 1591
