#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace lahman_odata	
{
	public partial class dimproduct
	{
		private int _productkey;
		public virtual int productkey
		{
			get
			{
				return this._productkey;
			}
			set
			{
				this._productkey = value;
			}
		}
		
		private string _productalternatekey;
		public virtual string productalternatekey
		{
			get
			{
				return this._productalternatekey;
			}
			set
			{
				this._productalternatekey = value;
			}
		}
		
		private int? _productsubcategorykey;
		public virtual int? productsubcategorykey
		{
			get
			{
				return this._productsubcategorykey;
			}
			set
			{
				this._productsubcategorykey = value;
			}
		}
		
		private string _weightunitmeasurecode;
		public virtual string weightunitmeasurecode
		{
			get
			{
				return this._weightunitmeasurecode;
			}
			set
			{
				this._weightunitmeasurecode = value;
			}
		}
		
		private string _sizeunitmeasurecode;
		public virtual string sizeunitmeasurecode
		{
			get
			{
				return this._sizeunitmeasurecode;
			}
			set
			{
				this._sizeunitmeasurecode = value;
			}
		}
		
		private string _englishproductname;
		public virtual string englishproductname
		{
			get
			{
				return this._englishproductname;
			}
			set
			{
				this._englishproductname = value;
			}
		}
		
		private string _spanishproductname;
		public virtual string spanishproductname
		{
			get
			{
				return this._spanishproductname;
			}
			set
			{
				this._spanishproductname = value;
			}
		}
		
		private string _frenchproductname;
		public virtual string frenchproductname
		{
			get
			{
				return this._frenchproductname;
			}
			set
			{
				this._frenchproductname = value;
			}
		}
		
		private decimal? _standardcost;
		public virtual decimal? standardcost
		{
			get
			{
				return this._standardcost;
			}
			set
			{
				this._standardcost = value;
			}
		}
		
		private bool _finishedgoodsflag;
		public virtual bool finishedgoodsflag
		{
			get
			{
				return this._finishedgoodsflag;
			}
			set
			{
				this._finishedgoodsflag = value;
			}
		}
		
		private string _color;
		public virtual string color
		{
			get
			{
				return this._color;
			}
			set
			{
				this._color = value;
			}
		}
		
		private short? _safetystocklevel;
		public virtual short? safetystocklevel
		{
			get
			{
				return this._safetystocklevel;
			}
			set
			{
				this._safetystocklevel = value;
			}
		}
		
		private short? _reorderpoint;
		public virtual short? reorderpoint
		{
			get
			{
				return this._reorderpoint;
			}
			set
			{
				this._reorderpoint = value;
			}
		}
		
		private decimal? _listprice;
		public virtual decimal? listprice
		{
			get
			{
				return this._listprice;
			}
			set
			{
				this._listprice = value;
			}
		}
		
		private string _size;
		public virtual string size
		{
			get
			{
				return this._size;
			}
			set
			{
				this._size = value;
			}
		}
		
		private string _sizerange;
		public virtual string sizerange
		{
			get
			{
				return this._sizerange;
			}
			set
			{
				this._sizerange = value;
			}
		}
		
		private double? _weight;
		public virtual double? weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				this._weight = value;
			}
		}
		
		private int? _daystomanufacture;
		public virtual int? daystomanufacture
		{
			get
			{
				return this._daystomanufacture;
			}
			set
			{
				this._daystomanufacture = value;
			}
		}
		
		private string _productline;
		public virtual string productline
		{
			get
			{
				return this._productline;
			}
			set
			{
				this._productline = value;
			}
		}
		
		private decimal? _dealerprice;
		public virtual decimal? dealerprice
		{
			get
			{
				return this._dealerprice;
			}
			set
			{
				this._dealerprice = value;
			}
		}
		
		private string _style;
		public virtual string style
		{
			get
			{
				return this._style;
			}
			set
			{
				this._style = value;
			}
		}
		
		private string _modelname;
		public virtual string modelname
		{
			get
			{
				return this._modelname;
			}
			set
			{
				this._modelname = value;
			}
		}
		
		private byte[] _largephoto;
		public virtual byte[] largephoto
		{
			get
			{
				return this._largephoto;
			}
			set
			{
				this._largephoto = value;
			}
		}
		
		private string _englishdescription;
		public virtual string englishdescription
		{
			get
			{
				return this._englishdescription;
			}
			set
			{
				this._englishdescription = value;
			}
		}
		
		private string _frenchdescription;
		public virtual string frenchdescription
		{
			get
			{
				return this._frenchdescription;
			}
			set
			{
				this._frenchdescription = value;
			}
		}
		
		private string _chinesedescription;
		public virtual string chinesedescription
		{
			get
			{
				return this._chinesedescription;
			}
			set
			{
				this._chinesedescription = value;
			}
		}
		
		private string _arabicdescription;
		public virtual string arabicdescription
		{
			get
			{
				return this._arabicdescription;
			}
			set
			{
				this._arabicdescription = value;
			}
		}
		
		private string _hebrewdescription;
		public virtual string hebrewdescription
		{
			get
			{
				return this._hebrewdescription;
			}
			set
			{
				this._hebrewdescription = value;
			}
		}
		
		private string _thaidescription;
		public virtual string thaidescription
		{
			get
			{
				return this._thaidescription;
			}
			set
			{
				this._thaidescription = value;
			}
		}
		
		private string _germandescription;
		public virtual string germandescription
		{
			get
			{
				return this._germandescription;
			}
			set
			{
				this._germandescription = value;
			}
		}
		
		private string _japanesedescription;
		public virtual string japanesedescription
		{
			get
			{
				return this._japanesedescription;
			}
			set
			{
				this._japanesedescription = value;
			}
		}
		
		private string _turkishdescription;
		public virtual string turkishdescription
		{
			get
			{
				return this._turkishdescription;
			}
			set
			{
				this._turkishdescription = value;
			}
		}
		
		private DateTime? _startdate;
		public virtual DateTime? startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				this._startdate = value;
			}
		}
		
		private DateTime? _enddate;
		public virtual DateTime? enddate
		{
			get
			{
				return this._enddate;
			}
			set
			{
				this._enddate = value;
			}
		}
		
		private string _status;
		public virtual string status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
	}
}
#pragma warning restore 1591
