#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace lahman_odata	
{
	public partial class master
	{
		private string _playerid;
		public virtual string playerid
		{
			get
			{
				return this._playerid;
			}
			set
			{
				this._playerid = value;
			}
		}
		
		private short? _birthyear;
		public virtual short? birthyear
		{
			get
			{
				return this._birthyear;
			}
			set
			{
				this._birthyear = value;
			}
		}
		
		private short? _birthmonth;
		public virtual short? birthmonth
		{
			get
			{
				return this._birthmonth;
			}
			set
			{
				this._birthmonth = value;
			}
		}
		
		private short? _birthday;
		public virtual short? birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				this._birthday = value;
			}
		}
		
		private string _birthcountry;
		public virtual string birthcountry
		{
			get
			{
				return this._birthcountry;
			}
			set
			{
				this._birthcountry = value;
			}
		}
		
		private string _birthstate;
		public virtual string birthstate
		{
			get
			{
				return this._birthstate;
			}
			set
			{
				this._birthstate = value;
			}
		}
		
		private string _birthcity;
		public virtual string birthcity
		{
			get
			{
				return this._birthcity;
			}
			set
			{
				this._birthcity = value;
			}
		}
		
		private short? _deathyear;
		public virtual short? deathyear
		{
			get
			{
				return this._deathyear;
			}
			set
			{
				this._deathyear = value;
			}
		}
		
		private short? _deathmonth;
		public virtual short? deathmonth
		{
			get
			{
				return this._deathmonth;
			}
			set
			{
				this._deathmonth = value;
			}
		}
		
		private short? _deathday;
		public virtual short? deathday
		{
			get
			{
				return this._deathday;
			}
			set
			{
				this._deathday = value;
			}
		}
		
		private string _deathcountry;
		public virtual string deathcountry
		{
			get
			{
				return this._deathcountry;
			}
			set
			{
				this._deathcountry = value;
			}
		}
		
		private string _deathstate;
		public virtual string deathstate
		{
			get
			{
				return this._deathstate;
			}
			set
			{
				this._deathstate = value;
			}
		}
		
		private string _deathcity;
		public virtual string deathcity
		{
			get
			{
				return this._deathcity;
			}
			set
			{
				this._deathcity = value;
			}
		}
		
		private string _namefirst;
		public virtual string namefirst
		{
			get
			{
				return this._namefirst;
			}
			set
			{
				this._namefirst = value;
			}
		}
		
		private string _namelast;
		public virtual string namelast
		{
			get
			{
				return this._namelast;
			}
			set
			{
				this._namelast = value;
			}
		}
		
		private string _namegiven;
		public virtual string namegiven
		{
			get
			{
				return this._namegiven;
			}
			set
			{
				this._namegiven = value;
			}
		}
		
		private short? _weight;
		public virtual short? weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				this._weight = value;
			}
		}
		
		private double? _height;
		public virtual double? height
		{
			get
			{
				return this._height;
			}
			set
			{
				this._height = value;
			}
		}
		
		private string _bats;
		public virtual string bats
		{
			get
			{
				return this._bats;
			}
			set
			{
				this._bats = value;
			}
		}
		
		private string _throws;
		public virtual string throws
		{
			get
			{
				return this._throws;
			}
			set
			{
				this._throws = value;
			}
		}
		
		private DateTime? _debut;
		public virtual DateTime? debut
		{
			get
			{
				return this._debut;
			}
			set
			{
				this._debut = value;
			}
		}
		
		private DateTime? _finalgame;
		public virtual DateTime? finalgame
		{
			get
			{
				return this._finalgame;
			}
			set
			{
				this._finalgame = value;
			}
		}
		
		private string _retroid;
		public virtual string retroid
		{
			get
			{
				return this._retroid;
			}
			set
			{
				this._retroid = value;
			}
		}
		
		private string _bbrefid;
		public virtual string bbrefid
		{
			get
			{
				return this._bbrefid;
			}
			set
			{
				this._bbrefid = value;
			}
		}
		
	}
}
#pragma warning restore 1591
